name: build application for dnac

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: src/dist/dnac-hc
